-- Phase 1 : EDA                                                                                                                                                                                                    -- phase 1 : Exploratory Data Analysis (EDA)
-- 1. Total revenue generated by the food delivery app 
SELECT SUM(order_amount-discount) AS total_revenue
FROM orders;

-- 2. Total order count per city
SELECT r.city, COUNT(*) AS total_orders
FROM orders o 
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC;

-- 3. Top ten customers by total spending   
SELECT c.name, SUM(o.order_amount - o.discount) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id
ORDER BY total_spent DESC
LIMIT 10;

-- Phase 2 : Customer Segmentation
-- 4. customer category (gold, silver, bronze)
SELECT 
    c.customer_id,
    c.name,
    CASE 
        WHEN SUM(o.order_amount - o.discount) > 1000 THEN 'Gold'
        WHEN SUM(o.order_amount - o.discount) > 500 THEN 'Silver'
        ELSE 'Bronze'
    END AS customer_category
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name;

-- Phase 3 : Restaurant performances    
-- 5. Top ten restaurants by total revenue
SELECT 
    r.restaurant_id,
    r.restaurant_name,
    r.city,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city
ORDER BY total_revenue DESC
LIMIT 10;

-- 6. Average rating of restaurants by city
SELECT city, AVG(rating) AS avg_rating
FROM restaurants
GROUP BY city  
ORDER BY avg_rating DESC;

-- Phase 4 : Delivery analysis
-- 7. Average delivery time per  city
SELECT r.city, AVG(o.delivery_time) AS avg_delivery_time
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id    
GROUP BY r.city
ORDER BY avg_delivery_time DESC;

-- 8. Late delivery time per city
SELECT r.city, COUNT(*) AS late_deliveries
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id    
WHERE o.delivery_time > 45  
GROUP BY r.city
ORDER BY late_deliveries DESC;  

-- Phase 5 : Payment & Discount Analysis
-- 9. Payment method distribution
SELECT payment_method, COUNT(*) AS payment_count
FROM orders
GROUP BY payment_method
ORDER BY payment_count DESC;

-- 10. Discount impact on revenue
SELECT discount, COUNT(*) AS discount_count
FROM orders
GROUP BY discount
ORDER BY discount_count DESC;

-- Phase 6 : Advanced SQL
-- 11. Monthly revenue using CTE
WITH Monthly_revenue AS (
    SELECT 
        month(order_date) AS month,
        SUM(order_amount - discount) AS revenue
    FROM orders
    GROUP BY month
)
SELECT month, revenue
FROM Monthly_revenue
ORDER BY month;

-- 12. Rank Restaurants by Revenue (Window Function)
WITH Ranked_restaurants AS (
    SELECT 
        r.restaurant_id,
        r.restaurant_name,
        SUM(o.order_amount - o.discount) AS total_revenue,
        RANK() OVER (ORDER BY SUM(o.order_amount - o.discount) DESC) AS revenue_rank
    FROM orders o
    JOIN restaurants r ON o.restaurant_id = r.restaurant_id
    GROUP BY r.restaurant_id, r.restaurant_name
)
SELECT * FROM Ranked_restaurants;

-- 13. Above Average Revenue Restaurants (Subquery)
SELECT 
    r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id 
GROUP BY r.restaurant_id, r.restaurant_name
HAVING SUM(o.order_amount - o.discount) > (
    SELECT AVG(order_amount - discount)
    FROM orders
)
ORDER BY total_revenue DESC;

-- Phase 7 : Database Objects 
-- 14. Creating revenue view
CREATE VIEW revenue_view AS
SELECT
        r.restaurant_id,
        r.restaurant_name,
        r.city,
        SUM(o.order_amount - o.discount) AS total_revenue
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city;

-- 15. Creating stored procedure Get Top N Restaurants
DELIMITER //
CREATE PROCEDURE GetTopNRestaurants(IN n INT)
BEGIN
    SELECT 
        r.restaurant_id,
        r.restaurant_name,
        r.city,
        SUM(o.order_amount - o.discount) AS total_revenue
    FROM orders o
    JOIN restaurants r ON o.restaurant_id = r.restaurant_id
    GROUP BY r.restaurant_id, r.restaurant_name, r.city
    ORDER BY total_revenue DESC
    LIMIT n;
END //
DELIMITER ;

-- Phase 8 : Performance Optimization 
-- 16. Index on order_date (for monthly reports)
CREATE INDEX idx_orders_order_date ON orders(order_date);

-- 17. Index customer name (for joins)
CREATE INDEX idx_customers_name ON customers(name);

-- 18. Index restaurant name (for joins)
CREATE INDEX idx_restaurants_name ON restaurants(restaurant_name);

-- Phase 9 : Automation Logic
-- 19. Auto log high value orders

CREATE TABLE high_value_orders_log (
    log_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    customer_id INT,
    restaurant_id INT,
    order_amount DECIMAL(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

create trigger trg_high_value_order
after insert on orders
for each row
begin
    if new.order_amount > 1000 then
        insert into high_value_order_log
        (order_id, customer_id, restaurant_id, order_amount)
        values 
        (new.order_id, new.customer_id, new.restaurant_id, new.order_amount);
    end if;
end;


insert into orders values (1010, 211, 138, '2024-01-01', 1200.00, 100.00, 'Credit Card', 30);
insert into orders values (1011, 212, 139, '2024-01-02', 800.00, 50.00, 'Cash', 25);

-- 20. Create a trigger to prevent negative discount
create trigger trg_prevent_negative_discount
before insert on orders
for each row
begin
    if new.discount < 0 then
        set new.discount = 0;
    end if;
end;    

insert into orders  values (1012, 213, 140, '2024-01-03', 500.00, -20.00, 'UPI', 20); 
-- discount will be set to 0 due to trigger
select * from orders where order_id = 1012;

-- 21. Create delivery delay warning trigger
create table delivery_delay_log (
    log_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    customer_id INT,
    restaurant_id INT,
    delivery_time INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

create trigger log_late_delivery
AFTER INSERT ON orders
for each row
BEGIN
    IF NEW.delivery_time > 45 THEN
        INSERT INTO delivery_delay_log (order_id, customer_id, restaurant_id, delivery_time)
        VALUES (NEW.order_id, NEW.customer_id, NEW.restaurant_id, NEW.delivery_time);
    END IF;
END;

insert into orders values (1018, 221, 110, '2024-01-04', 600.00, 30.00, 'Credit Card', 50);
